# DB
spring.datasource.url=jdbc:mysql://gyujinmysql1.mysql.database.azure.com/shop
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update

# AWS S3
spring.cloud.aws.credentials.accessKey=${AWS_ACCESS_KEY}
spring.cloud.aws.credentials.secretKey=${AWS_SECRET_KEY}
spring.cloud.aws.s3.bucket=gyujinspring1
spring.cloud.aws.region.static=ap-northeast-2

# Corretto 17 running on 64bit Amazon Linux 2023/4.9.0
# default port num 8080
# NGINX port num 5000
server.port=5000

server.servlet.session.timeout=6m
server.servlet.session.cookie.max-age=6m